### PR TITLE
Add option to allocate empty group on heap

### PR DESCRIPTION
**Pull request by AgostonSzepessy**
We were using phmap with an allocator backed by a memory mapped file. When we loaded the file again and mapped it back into memory, we got intermittent crashes. The culprit was `EmptyGroup()`.

`EmptyGroup()` was allocating `empty_group` inside the process space, and not inside the memory mapped space. When another process loaded up the memory mapped file, the `empty_group` pointed outside the address space. This caused a crash.

To fix this, `PHMAP_NO_STATIC_EMPTY_GROUP` is introduced. If it's defined, phmap will use the allocator given to it to allocate the `empty_group`.

### CODE REVIEW

**Comment by greg7mdp** [comment]
Thank you @AgostonSzepessy , this is an excellent PR, thanks for finding this issue.

One think I don't like is the `PHMAP_NO_STATIC_EMPTY_GROUP`. Why not always allocate the `emptygroup` if the allocator is not the default `allocator_type()`. So you could have `emptygroup()` be something like:

```
template <class ALLOC, class DEFAULT_ALLOC>
inline ctrl_t* EmptyGroup([[maybe_unused]] ALLOC& alloc, DEFAULT_ALLOC&) {
  alignas(16) static constexpr ctrl_t empty_group[] = {
      kSentinel, kEmpty, kEmpty, kEmpty, kEmpty, kEmpty, kEmpty, kEmpty,
      kEmpty,    kEmpty, kEmpty, kEmpty, kEmpty, kEmpty, kEmpty, kEmpty};
  PHMAP_IF_CONSTEXPR (std::is_same<ALLOC, DEFAULT_ALLOC>::value)
      return const_cast<ctrl_t*>(empty_group);
  else {
      static ctrl_t* ptr_empty_group = InitializeEmptyGroup<alignment>(empty_group, alloc);
      return ptr_empty_group;
  }
}
```

Although I don't really like the static, as two hash maps can be created with two different allocators within the same process. I think we should add a `ctrl_t* empty_group;` member to `raw_hash_set` which is initialized at construction.

**Comment by AgostonSzepessy** [comment]
Thanks for the review @greg7mdp! Those are good suggestions; I'll incorporate them soon and push an update.

**Comment by greg7mdp** [comment]
> Thanks for the review @greg7mdp! Those are good suggestions; I'll incorporate them soon and push an update.

Hi @AgostonSzepessy, I though about this overnight, and adding a member and allocating it for an empty table is probably not the best solution (one problem is that it increases the memory usage of empty tables). Let me think about this some more.

**Comment by greg7mdp** [comment]
Maybe we do away with the `emptygroup()` alltogether.

**Comment by AgostonSzepessy** [comment]
Actually, I think your first suggestion might the best.

> Although I don't really like the static, as two hash maps can be created with two different allocators within the same process. 

Since the function is templated on the allocator, each allocator would get its own magic static (here's a [link](https://www.ibm.com/docs/en/xl-c-and-cpp-aix/16.1?topic=only-static-data-members-templates-c) that confirms this). That allows people to use different allocators within the same process and they wouldn't trample over each other. What do you think?

**Comment by greg7mdp** [comment]
> What do you think?

I think I have a better solution, which is to not have an `emptygroup` *unless* the map is using the std::allocator. I'm working on it just now, give me a few minutes and we can discuss.

**Comment by greg7mdp** [comment]
Sorry @AgostonSzepessy , it took longer than expected, but I have my changes ready [here](https://github.com/greg7mdp/parallel-hashmap/pull/254/files). Please let me know what you think.

**Comment by greg7mdp** [comment]
> Since the function is templated on the allocator, each allocator would get its own magic static

It is templated on the allocator type, not the allocator object. You could have a type of allocator allocating from memory mapped files, but two instances of this allocator allocating from different files, and their offset pointers pointing to different memory mapped segments.

**Comment by AgostonSzepessy** [comment]
I left a comment on the other PR. Thank you for looking into this so quickly!

**Pull request closed without merging**
