### PR TITLE
added check for <shared_mutex>, made Throw() a macro

### PR DESCRIPTION
**Pull request by ilobilo**

### CODE REVIEW

**Comment by greg7mdp** [comment]
Why make `Throw` a macro?

**Comment by ilobilo** [comment]
Because with a macro ``std::*_error`` objects will not be constructed unless exceptions are enabled. (and those classes are not implemented where I use this project)

**Comment by greg7mdp** [comment]
Thanks for the issue and input.
I was not able to accept your PR as is, because it did not compile (see checks above), so I made `Throw` a macro, but with a more specific name.
I also improved the check for `<shared_mutex>`.
Also please avoid whitespace changes next time.

**Comment by ilobilo** [comment]
Thanks

**Pull request closed without merging**
