### PR TITLE
added load&dump interface

### PR DESCRIPTION
**Pull request by gtarcoder**

### CODE REVIEW

**Comment by gtarcoder** [comment]
@greg7mdp  Hi Gregory, I want to add load and dump interface for set&map instead of using cereal. Could you help to review that? Any comment would be appreciated.

**Comment by greg7mdp** [comment]
Hi @gtarcoder,

Thanks for the change. The tests fail line 3298:

/Users/travis/build/greg7mdp/parallel-hashmap/parallel_hashmap/phmap.h:3298:34: error: use of undeclared identifier 'dump_path'
            if (!inner.set_.dump(dump_path)) {

**Comment by gtarcoder** [comment]
> Hi @gtarcoder,
> 
> Thanks for the change. The tests fail line 3298:
> 
> /Users/travis/build/greg7mdp/parallel-hashmap/parallel_hashmap/phmap.h:3298:34: error: use of undeclared identifier 'dump_path'
> if (!inner.set_.dump(dump_path)) {

Hi @greg7mdp  ， have fixed errors now.  And have made more changes to this PR, any comments ?

**Comment by greg7mdp** [comment]
The `IsStringOrArithmeticType` check is not right, If you used long strings in your test you would see that the dump does not work because the string has an internal pointer. In any case I think you should use [is_trivially_copyable](https://en.cppreference.com/w/cpp/types/is_trivially_copyable) instead because this is exactly what we need for the dump.

Somehow I tried updating your change and I messed up my local github repository... trying to fix it - I have a support ticket with github.

**Comment by greg7mdp** [comment]
Hi @gtarcoder , I merged your pull request by mistake, and then I undid it. Sorry about that!

**Comment by greg7mdp** [comment]
@gtarcoder , please submit a new pull request please.

**Comment by gtarcoder** [comment]
> @gtarcoder , please submit a new pull request.

Hi @greg7mdp , sorry for troubles, I will create a new PR.

**Pull request merged**
