### PR TITLE
add for_each extension api for safe keys iteration

### PR DESCRIPTION
**Pull request by amitma1**

### CODE REVIEW

**Comment by greg7mdp** [comment]
Nice! Thanks for the new API!

**Comment by amitma1** [comment]
You're welcome!
I'd lie if I said I understand the whole code base, so I hope I've done it well 😅

**Comment by greg7mdp** [comment]
Hi @amitma1 ,

Thanks again for the changes. I just checked in a modified version which also has a version allowing to change the values. I was trying it in my machine and it was just easier to check it in directly, I hope it is OK with you!

**Comment by amitma1** [comment]
Hi @greg7mdp!

I really appreciate the quick response! Your changes look great and well suit my needs, I have looked and tested them, and they seem to work really well.

The solution you used with `std::for_each` is definitely nicer than mine :)
I used the `parallel_hash_set` iterator because I thought I had to call on `skip_empty()` just like done in the `begin()` function.
But using the internal submaps iterator is way more robust :)

Thanks again for the changes, I really appreciate it :D

**Comment by greg7mdp** [comment]
Hey, thanks to you, I do appreciate you using phmap and taking the time to suggest a useful change and even submit a PR. Don't hesitate to do it again if you feel so enclined.

**Pull request closed without merging**
