### PR TITLE
Add thread-safe accessors to parallel_hash_map

### PR DESCRIPTION
**Pull request by bpmckinnon**
I've created two functions that should provide thread-safe access to the values of the map.  The first copies and returns the value behind the shareable lock.  The second passes a reference value to a functor behind the shareable lock, which allows the user to copy only part of the value.  Both return true if contains is true.

I'm not if both should be named if_contains or contains, though I think they should both have the same name.  Currently the first is named contains, the second is if_contains.

### CODE REVIEW

**Comment by greg7mdp** [comment]
Many thanks, Brian, your changes look great. There are a couple build issues on linux, looks like it needs `this->hash(key)` instead of just `hash(key)` in two places. Great that you added the tests as well. 
I think I'd rather both be called `if_contains()`, just because I don't want to use the same name as the standard function. If we reuse `contains`, it is possible that in the future they could add overloads that conflict with ours.

**Comment by greg7mdp** [comment]
I see you just made the fix. Thanks!

**Comment by bpmckinnon** [comment]
I managed to get the contains function renamed, but I had to use a bit of an ugly enable_if setup to get around the operator.  I didn't see any other instances of this in the code, so I'm wondering do you have any better solution?

**Comment by greg7mdp** [comment]
Hi Brian, really sorry to cause these issues, I didn't realize the renaming would be problematic. 

Could you use just one templated argument in the first `if_contains`, as in:

```
template <class K = key_type>
bool if_contains(const key_arg<K>& key, mapped_type& v) const
```

I think this will be enough to resolve the ambiguity. 

Still, maybe leave your `enable_if<is_invocable` I think it is a good thing to check.

**Comment by bpmckinnon** [comment]
I've got the change and it works, but I'm not sure if it much clearer than what is there atm.  Alternately the functions could just be renamed so they are more explicit, like if_contains_copy and if_contains_call.  Any of the three options (keep, change, rename) work for me, just let me know which one is your favorite.

**Comment by greg7mdp** [comment]
I'd prefer option 2 (change to one templated argument in the first if_contains) unless you feel there is a benefit to have the second templated argument. Also thanks for updating the README.

**Comment by greg7mdp** [comment]
Or even better, please remove the `if_contains` that takes a mapped_value. After all the user can easily implement it using the other version if desired. Also it keeps the API to a minimum which I think is preferable.

**Comment by bpmckinnon** [comment]
Yeah, that really cleaned up the interface.

**Comment by bpmckinnon** [comment]
Wrong button

**Pull request merged**
