### PR TITLE
Added dump&&load interface for trivially_copyable types

### PR DESCRIPTION
**Pull request by gtarcoder**
I need to dump and load the hash map/set very quickly for trivially_copyable types such as uint32,uint64  and so on.
Fortunately all necessary data of these types are stored in ctrl_ and slots_ area so we can dump&load ctrl_ and slots_ directly.

### CODE REVIEW

**Comment by gtarcoder** [comment]
Hi @greg7mdp , need your review again, thanks for your time

**Comment by gtarcoder** [comment]
Hi @greg7mdp , could you help to review again?

**Comment by greg7mdp** [comment]
Hi @gtarcoder I will review but it may take me a few days. I am very busy with things this week. 
One thing I would like is to have the new code (and the three #include statements) not in `phmap.h` and `phmap_base.h`, but in a separate file (maybe `phmap_dump.h`, that people can include inf they want this functionality. 

Also, do we need the code with PairTraits? Does  std::is_trivially_copyable not work with a std::pair?

**Comment by greg7mdp** [comment]
Never mind, I looked into it and I see you do need the PairTraits, Can you also move that to phmap_dump.h?

Thanks!

**Comment by greg7mdp** [comment]
Please replace your change in phmap_base.h with this:

```
#if defined(__GLIBCXX__) && __GLIBCXX__ < 20150801
    template<typename T> struct is_trivially_copyable : public std::integral_constant<bool, __has_trivial_copy(T)> {};
#else
    template<typename T> struct is_trivially_copyable : public std::is_trivially_copyable<T> {};
#endif

template <class T1, class T2>
struct is_trivially_copyable<std::pair<T1, T2>> {
    static constexpr bool value = is_trivially_copyable<T1>::value && is_trivially_copyable<T2>::value;
};
```

and use `std::enable_if<type_traits_internal::is_trivially_copyable<...>`

**Comment by gtarcoder** [comment]
> Please replace your change in phmap_base.h with this:
> 
> ```
> #if defined(__GLIBCXX__) && __GLIBCXX__ < 20150801
>     template<typename T> struct IsTriviallyCopyable : public std::integral_constant<bool, __has_trivial_copy(T)> {};
> #else
>     template<typename T> struct IsTriviallyCopyable : public std::is_trivially_copyable<T> {};
> #endif
> 
> template <class T1, class T2>
> struct IsTriviallyCopyable<std::pair<T1, T2>> {
>     static constexpr bool value = IsTriviallyCopyable<T1>::value && IsTriviallyCopyable<T2>::value;
> };```
> 
> and use `std::enable_if<type_traits_internal::IsTriviallyCopyable<...>`
> ```

got that, great solution. Will push a new commit later

**Comment by greg7mdp** [comment]
Hi @gtarcoder,
Thanks a lot for the change. This looks very good, but I don't think the mmap code is ready to merge yet. There would not be much benefit in just loading the data using mmap like this, it probably would not be faster than doing the regular load. The benefit would be if we used mmap for the actual table, instead of new/delete.
If you remove the mmap code, I'll push the change. Next we can look into adding full mmap support.

**Comment by greg7mdp** [comment]
Thanks for the changes @gtarcoder!

**Comment by gtarcoder** [comment]
> Hi @gtarcoder,
> Thanks a lot for the change. This looks very good, but I don't think the mmap code is ready to merge yet. There would not be much benefit in just loading the data using mmap like this, it probably would not be faster than doing the regular load. The benefit would be if we used mmap for the actual table, instead of new/delete.
> If you remove the mmap code, I'll push the change. Next we can look into adding full mmap support.

Hi @greg7mdp  ,  thanks for your very good comments and the final merge.  will continue to pay attention to this repo.

**Comment by greg7mdp** [comment]
Hi @gtarcoder, I made some small changes in your test and example programs. I put brackets around the load/dump calls so that the archive file is closed (which happens in the destructor). Thanks - greg

**Comment by gtarcoder** [comment]
> Hi @gtarcoder, I made some small changes in your test and example programs. I put brackets around the load/dump calls so that the archive file is closed (which happens in the destructor). Thanks - greg

Hi @greg7mdp , find your new changes, they are more concise and clean. Great!

**Comment by josix** [comment]
> Hi @gtarcoder, Thanks a lot for the change. This looks very good, but I don't think the mmap code is ready to merge yet. There would not be much benefit in just loading the data using mmap like this, it probably would not be faster than doing the regular load. The benefit would be if we used mmap for the actual table, instead of new/delete. If you remove the mmap code, I'll push the change. Next we can look into adding full mmap support.

Hello @greg7mdp, do you have suggestions about how to implement the mmap feature for keeping the whole table? I'm planning to make it for reducing memory usage when using the hashtable in multiprocessing in python scripts. The processes actually access the same pre-built and read-only hashtable so I would like to load it through the memory-mapped file to share the same table and keep memory usage lower. Is this could be achieved by using `boost::interprocess::managed_mapped_file::managed_mapped_file`? Or there are other suggested methods? Thanks!

**Comment by greg7mdp** [comment]
@josix why don't you try using a `boost::interprocess::allocator` based on `managed_mapped_file::segment_manager`, like in https://gist.github.com/DmitryKhlus/d89f5a226c37d9523ea6.
I'm not 100% sure that phmap will support it now, but it is worth a try!

**Comment by josix** [comment]
> @josix why don't you try using a `boost::interprocess::allocator` based on `managed_mapped_file::segment_manager`, like in https://gist.github.com/DmitryKhlus/d89f5a226c37d9523ea6.
> I'm not 100% sure that phmap will support it now, but it is worth a try!

Thanks for the advice! Actually, I'm not quite familiar with the cpp ecosystem. The reference helps a lot. Let me try it.

**Comment by greg7mdp** [comment]
If your code using this allocator works with `std::unordered_map`, but not with the phmap containers, please let me know and I'll investigate.

**Pull request merged**
